<?php

  use Drupal\node\Entity\Node;
  use Drupal\Core\Cache\Cache;

  /**
   * Implements hook_views_pre_view().
   */
  function johns_module_views_pre_view(&$view) {
    if($view->id() == 'most_popular_content' && $view->current_display == 'page_1' || $view->id() == 'most_popular_content' && $view->current_display == 'block_1') {
      // Country identified from language code because use can't switch language.
      $lc = \Drupal::languageManager()->getCurrentLanguage()->getId();
      $filters = $view->display_handler->getOption('filters');
      if ($filters['field_related_tags_value']) {
        foreach ($filters['field_related_tags_value']['value'] as $key => $filter) {
              
          // Indian nodes with from any language. 
          if ($key == 2 && $lc == 'hi') {
            unset($filters['field_related_tags_value']['value'][$key]);
          }
              
          // Pakistan nodes with from any language. 
          if ($key == 1 && $lc == 'ur') {
            unset($filters['field_related_tags_value']['value'][$key]);
          }

          // Anywhere
          if ($lc == 'en') {
            unset($filters['field_related_tags_value']['value'][$key]);
          }
        }
      }
      $view->display_handler->overrideOption('filters', $filters);

      // Adding custom cache tags
      $view->element['#cache']['tags'] = ['language:' . $lc];
    }
  }


/**
 * Implements hook_ENTITY_TYPE_insert().
 * 
 * Invalidate code during new node creation time.
 */
function johns_module_node_insert(Node $node) {
  if ($node->bundle() == 'article') {
    Cache::invalidateTags(array('language:en'));
    Cache::invalidateTags(array('language:hi'));
    Cache::invalidateTags(array('language:ur'));
  }
}